apiVersion: v1
kind: Service
metadata:
  name: my-app2-2907
spec:
  selector:
    app: my-app2-2907
  ports:
  - name: http
    protocol: TCP
    port: 6005
    targetPort: 5005
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2-2907
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2-2907
  template:
    metadata:
      labels:
        app: my-app2-2907
    spec:
      containers:
      - name: my-app2-2907
        image: phanick/my-app2-2907:2
        imagePullPolicy: Never
        ports:
        - containerPort: 5005
