apiVersion: v1
kind: Service
metadata:
  name: my-py-app2
spec:
  selector:
    app: my-py-app2
  ports:
  - name: http
    protocol: TCP
    port: 6005
    targetPort: 5005
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-py-app2
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-py-app2
  template:
    metadata:
      labels:
        app: my-py-app2
    spec:
      containers:
      - name: my-py-app2
        image: phanick/my-py-app2:2
        imagePullPolicy: Never
        ports:
        - containerPort: 5005
