apiVersion: v1
kind: Service
metadata:
  name: my-app1-061
spec:
  selector:
    app: my-app1-061
  ports:
  - name: http
    protocol: TCP
    port: 6001
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1-061
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app1-061
  template:
    metadata:
      labels:
        app: my-app1-061
    spec:
      containers:
      - name: my-app1-061
        image: phanick/my-app1-061:1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
