apiVersion: v1
kind: Service
metadata:
  name: ${APP_TWO}
spec:
  selector:
    app: ${APP_TWO}
  ports:
  - name: http
    protocol: TCP
    port: 6005
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_TWO}
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_TWO}
  template:
    metadata:
      labels:
        app: ${APP_TWO}
    spec:
      containers:
      - name: ${APP_TWO}
        image: phanick/${APP_TWO}:2
        imagePullPolicy: Always
        restartPolicy: Always
        ports:
        - containerPort: 5000
