apiVersion: v1
kind: Service
metadata:
  name: my-app1-2907
spec:
  selector:
    app: my-app1-2907
  ports:
  - name: http
    protocol: TCP
    port: 6001
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app1-2907
  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1-2907
  template:
    metadata:
      labels:
        app: my-app1-2907
    spec:
      containers:
      - name: my-py-app1
        image: phanick/my-app1-2907:1
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
