apiVersion: v1
kind: Service
metadata:
  name: my-app2-062
spec:
  selector:
    app: my-app2-062
  ports:
  - name: http
    protocol: TCP
    port: 6005
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app2-062
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app2-062
  template:
    metadata:
      labels:
        app: my-app2-062
    spec:
      containers:
      - name: my-app2-062
        image: phanick/my-app2-062:2
        imagePullPolicy: Always
        restartPolicy: Always
        ports:
        - containerPort: 5000
